version: '3.8'

services:
  certificate-generator:
    build: .
    ports:
      - "5001:5001"
    environment:
      - CERTIFICATE_PORT=5001
      - PDF_ENGINE=playwright
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:3010
    volumes:
      - ./output:/app/output
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching certificates
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: